#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("tpSNCF.Resource", IsApplication=true)]

namespace tpSNCF
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int btnListe = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int btnNewAgent = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int lvActivites = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int lvFormations = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int textView1 = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int txtLibelle = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int txtNomFormation = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int txtNumero = 2130968578;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int choixActivity = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ItemActivite = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ItemFormation = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Main = 2130837507;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int app_ip = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
